apiVersion: v1
kind: Service
metadata:
  name: gawachabazaar-backend
  namespace: gawachabazaar
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  type: ClusterIP
  selector:
    app: gawachabazaar-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
