"""create_phase_2_farm_and_traceability_tables

Revision ID: 56f5c455d612
Revises: 23d1924630c2
Create Date: 2026-09-04 18:12:28.593911

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56f5c455d612"
down_revision: str | None = "23d1924630c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "farms",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("owner_user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("address_line_1", sa.String(length=255), nullable=False),
        sa.Column("address_line_2", sa.String(length=255), nullable=True),
        sa.Column("village", sa.String(length=150), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("district", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("contact_number", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')", name="ck_farms_status"
        ),
        sa.CheckConstraint(
            "latitude IS NULL OR (latitude >= -90.0 AND latitude <= 90.0)",
            name="ck_farms_latitude",
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR (longitude >= -180.0 AND longitude <= 180.0)",
            name="ck_farms_longitude",
        ),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_farms_owner_user_id", "farms", ["owner_user_id"], unique=False)
    op.create_index("ix_farms_status", "farms", ["status"], unique=False)
    op.create_table(
        "batches",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("farm_id", sa.BigInteger(), nullable=False),
        sa.Column("batch_code", sa.String(length=100), nullable=False),
        sa.Column("harvest_date", sa.Date(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('HARVESTED', 'COLLECTED', 'SORTED', 'GRADED', 'APPROVED', 'REJECTED', 'EXPIRED')",
            name="ck_batches_status",
        ),
        sa.CheckConstraint(
            "unit IN ('KG', 'G', 'L', 'ML', 'UNIT', 'DOZEN', 'BOX', 'CRATE')",
            name="ck_batches_unit",
        ),
        sa.CheckConstraint(
            "expiry_date IS NULL OR expiry_date >= harvest_date",
            name="ck_batches_expiry_date",
        ),
        sa.CheckConstraint("quantity > 0", name="ck_batches_quantity"),
        sa.ForeignKeyConstraint(["farm_id"], ["farms.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_code", name="uq_batches_batch_code"),
    )
    op.create_index("ix_batches_farm_id", "batches", ["farm_id"], unique=False)
    op.create_index(
        "ix_batches_harvest_date", "batches", ["harvest_date"], unique=False
    )
    op.create_index("ix_batches_status", "batches", ["status"], unique=False)
    op.create_table(
        "quality_checks",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("batch_id", sa.BigInteger(), nullable=False),
        sa.Column("checked_by_user_id", sa.BigInteger(), nullable=False),
        sa.Column("checked_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'PASSED', 'FAILED')", name="ck_quality_checks_status"
        ),
        sa.ForeignKeyConstraint(["batch_id"], ["batches.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["checked_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_quality_checks_batch_id", "quality_checks", ["batch_id"], unique=False
    )
    op.create_index(
        "ix_quality_checks_checked_by_user_id",
        "quality_checks",
        ["checked_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_quality_checks_checked_on", "quality_checks", ["checked_on"], unique=False
    )
    op.create_index(
        "ix_quality_checks_status", "quality_checks", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_quality_checks_status", table_name="quality_checks")
    op.drop_index("ix_quality_checks_checked_on", table_name="quality_checks")
    op.drop_index("ix_quality_checks_checked_by_user_id", table_name="quality_checks")
    op.drop_index("ix_quality_checks_batch_id", table_name="quality_checks")
    op.drop_table("quality_checks")
    op.drop_index("ix_batches_status", table_name="batches")
    op.drop_index("ix_batches_harvest_date", table_name="batches")
    op.drop_index("ix_batches_farm_id", table_name="batches")
    op.drop_table("batches")
    op.drop_index("ix_farms_status", table_name="farms")
    op.drop_index("ix_farms_owner_user_id", table_name="farms")
    op.drop_table("farms")
    # ### end Alembic commands ###
