"""add_category_image_url

Revision ID: 6f335f6934e6
Revises: a1024b757d60
Create Date: 2026-09-16 09:24:04.049856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f335f6934e6'
down_revision: Union[str, None] = 'a1024b757d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'image_url')
    # ### end Alembic commands ###
